apiVersion: v1
kind: Pod
metadata:
  name: uperf-client
spec:
  nodeSelector: {"kubernetes.io/hostname": "appworker-1.blueprint-cwl.nokia.core.bos2.lab"}
  runtimeClassName: performance-app-worker-profile
  containers:
  - name: my-uperf
    image: quay.io/hnhan/ocp-tools:uperf
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
              cpu: 2
              memory: 2048Mi
      limits:
              cpu: 2
              memory: 2048Mi
    securityContext: 
       privileged: true
       capabilities: { "add": [ "SYS_ADMIN", "IPC_LOCK", "SYS_NICE", "SYS_ADMIN" ] }

