---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: mcp-mlx-vf
  name: 99-pci-realloc-mcp-mlx-vf
spec:
  config:
    ignition:
      version: 3.2.0
  kernelArguments:
      - pci=realloc
